import { LES_TALEN } from './lesTaal.js';

/**
 * De vaste schermteksten van de leerlingroute in de taal van de leerling.
 *
 * De lesstof zelf gaat langs het model (zie `lesTaal.js` en de Cloud Functions
 * `vertaalLesblok` en `vertaalLesstofInfo`); dit bestand gaat over de woorden
 * die HELIX zelf zegt: "Ga verder", "Wat je gaat leren:", "3 van 7 onderdelen
 * af". Die horen niet bij een vertaalmodel thuis. Ze veranderen bijna nooit, ze
 * moeten altijd hetzelfde luiden, en een leerling mag nooit op een vertaling
 * van een knop hoeven wachten.
 *
 * Eén blok per taal, met dezelfde sleutels. Een taal erbij is dus één blok plus
 * een regel in LES_TALEN, en niet tachtig losse regels bijwerken. Een
 * ontbrekende sleutel of taal valt terug op het Nederlands: liever een
 * Nederlands woord dan een leeg scherm. `controleerWoordenboekCompleet` bewaakt
 * in de tests dat er niets ontbreekt en dat elke vertaling dezelfde
 * plaatshouders gebruikt.
 *
 * Plaatshouders staan tussen accolades: `{done} van {total} onderdelen af`.
 */

const NL = {
  'lesstof.kop': 'Lesstof',
  'lesstof.titel': 'Jouw lesstof',
  'lesstof.laden': 'Lesstof laden',
  'lesstof.leeg.titel': 'Nog geen lesstof klaargezet voor jouw klas',
  'lesstof.leeg.tekst': 'Je docent zet hier straks lessen voor je klaar.',
  'verder.kop': 'Verder waar je was',
  'verder.klaar.titel': 'Je bent bij',
  'verder.klaar.tekst': 'Alles wat klaarstaat heb je af. Kies hieronder een hoofdstuk om iets terug te lezen.',
  'status.nietBegonnen': 'nog niet begonnen',
  'knop.beginnen': 'Beginnen',
  'knop.gaVerder': 'Ga verder',
  'knop.openen': 'Openen',
  'knop.bekijkTerug': 'Bekijk terug',
  'knop.verder': 'Verder',
  'knop.start': 'Start',
  'knop.opnieuw': 'Opnieuw',
  'hoofdstuk.kop': 'Hoofdstuk',
  'hoofdstuk.kopMetNummer': 'Hoofdstuk {nummer}',
  'hoofdstuk.af': 'Dit hoofdstuk is af',
  'hoofdstuk.aantal.een': '1 hoofdstuk',
  'hoofdstuk.aantal.meer': '{aantal} hoofdstukken',
  'paragraaf.aantal.een': '1 paragraaf',
  'paragraaf.aantal.meer': '{aantal} paragrafen',
  'onderdeel.aantal.een': '1 onderdeel',
  'onderdeel.aantal.meer': '{aantal} onderdelen',
  'onderdeel.geen': 'Nog geen gepubliceerde onderdelen',
  'onderdeel.af': '{done} van {total} onderdelen af',
  'leerdoel.aantal.een': '1 leerdoel',
  'leerdoel.aantal.meer': '{aantal} leerdoelen',
  'rubriek.onderdelen': 'Onderdelen',
  'rubriek.voortgang': 'Voortgang',
  'rubriek.introductie': 'Introductie',
  'rubriek.voorkennis': 'Voorkennis',
  'rubriek.paragrafen': 'Paragrafen',
  'rubriek.oefentoetsen': 'Oefentoetsen',
  'rubriek.toetsen': 'Toetsen',
  'hoofdstuk.waarover': 'Waar dit hoofdstuk over gaat',
  'knop.opnieuwBekijken': 'Opnieuw bekijken',
  'knop.toonMinder': 'Toon minder',
  'knop.toonAlles': 'Toon alles ({aantal})',
  'knop.toonAllesPlus': 'Toon alles ({aantal}) - ook de plusparagrafen',
  'knop.startOnderdeel': 'Start dit onderdeel',
  'knop.beginBijStap1': 'Begin bij stap 1',
  'knop.kopieerLink': 'Kopieer link',
  'knop.meerOpties': 'Meer opties',
  'knop.terugNaarOverzicht': 'Terug naar overzicht',
  'status.af': 'af',
  'paragraaf.geenOnderdelen': 'Je docent heeft voor deze paragraaf nog geen onderdelen klaargezet.',
  'hoofdstuk.laden': 'Hoofdstuk laden',
  'hoofdstuk.nietVoorJou.titel': 'Dit hoofdstuk staat niet voor jou klaar',
  'hoofdstuk.nietVoorJou.tekst': 'Misschien is de link oud, of heeft je docent het hoofdstuk nog niet gedeeld.',
  'nogTeDoen.kop': 'Nog te doen',
  'nogTeDoen.klaar': 'Dit hoofdstuk is af.',
  'nogTeDoen.rest': 'en nog {aantal} andere',
  'melding.linkGekopieerd': 'Link gekopieerd.',
  'melding.kopierenMislukt': 'Kopiëren is niet gelukt.',
  'melding.kopierenKanNiet': 'Kopiëren lukt niet in deze browser.',
  'rubriek.paragraaf': 'Paragraaf',
  'les.kop': 'Les',
  'les.leerdoelen': 'Leerdoelen',
  'les.inDitHoofdstuk': 'In dit hoofdstuk',
  'les.onderdeelVan': 'Onderdeel {nummer} van {totaal}',
  'les.terugNaarHoofdstuk': 'Terug naar het hoofdstuk',
  'les.paragraafAfronden': 'Paragraaf afronden',
  'les.volledigScherm': 'Volledig scherm',
  'status.afgerond': 'Afgerond',
  'status.nogNietAf': 'Nog niet af',
  'knop.vorige': 'Vorige',
  'knop.volgendeStap': 'Volgende stap',
  'les.afronden': 'Les afronden',
  'intro.watJeGaatLeren': 'Wat je gaat leren:',
  'intro.stappen.een': '1 stap',
  'intro.stappen.meer': '{aantal} stappen',
  'plus.label': 'Plus - vrijwillig',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'Hoeft niet - mag wel',
  'plus.extraAf': 'Plus: {done} van {total} extra af',
  'plus.staatKlaar': 'Plusstof staat klaar als je meer wilt',
  'plus.uitleg': 'Deze paragraaf is vrijwillig. Hij telt niet mee voor je hoofdstuk en je hoeft hem niet af te '
    + 'hebben om verder te mogen. Een aanrader als je later naar de havo wilt - en je verdient er '
    + 'gewoon tokens mee.',
  'slot.label': 'Nog op slot',
  'slot.titel': 'Dit hoofdstuk staat nog op slot',
  'slot.uitleg': 'Je docent zet dit hoofdstuk open als de les begint.',
  'slot.komtEraan': 'De lessen van dit hoofdstuk komen eraan.',
  'tijd.minuten': '{aantal} min',
  'tijd.uren': '{uren} uur',
  'tijd.urenMinuten': '{uren} uur {minuten} min',
  'profiel.taal.kop': 'Taal van je lessen',
  'profiel.taal.uitleg': 'Kies de taal waarin je de uitleg wilt lezen. Je antwoorden schrijf je in het Nederlands.',
  'profiel.taal.nederlands': 'Alleen Nederlands',
  'profiel.taal.opgeslagen': 'Opgeslagen.',
  'profiel.taal.mislukt': 'Opslaan lukte niet. Probeer het zo nog eens.'
};

const EL = {
  'lesstof.kop': 'Μαθήματα',
  'lesstof.titel': 'Τα μαθήματά σου',
  'lesstof.laden': 'Φόρτωση μαθημάτων',
  'lesstof.leeg.titel': 'Δεν υπάρχει ακόμα ύλη για την τάξη σου',
  'lesstof.leeg.tekst': 'Ο καθηγητής σου θα βάλει σύντομα μαθήματα εδώ.',
  'verder.kop': 'Συνέχισε από εκεί που έμεινες',
  'verder.klaar.titel': 'Είσαι εντάξει',
  'verder.klaar.tekst': 'Τελείωσες όλα όσα ήταν έτοιμα. Διάλεξε ένα κεφάλαιο παρακάτω για να το ξαναδιαβάσεις.',
  'status.nietBegonnen': 'δεν έχει ξεκινήσει ακόμα',
  'knop.beginnen': 'Ξεκίνα',
  'knop.gaVerder': 'Συνέχισε',
  'knop.openen': 'Άνοιξε',
  'knop.bekijkTerug': 'Δες ξανά',
  'knop.verder': 'Συνέχεια',
  'knop.start': 'Ξεκίνα',
  'knop.opnieuw': 'Ξανά',
  'hoofdstuk.kop': 'Κεφάλαιο',
  'hoofdstuk.kopMetNummer': 'Κεφάλαιο {nummer}',
  'hoofdstuk.af': 'Αυτό το κεφάλαιο ολοκληρώθηκε',
  'hoofdstuk.aantal.een': '1 κεφάλαιο',
  'hoofdstuk.aantal.meer': '{aantal} κεφάλαια',
  'paragraaf.aantal.een': '1 παράγραφος',
  'paragraaf.aantal.meer': '{aantal} παράγραφοι',
  'onderdeel.aantal.een': '1 μέρος',
  'onderdeel.aantal.meer': '{aantal} μέρη',
  'onderdeel.geen': 'Δεν υπάρχουν ακόμα δημοσιευμένα μέρη',
  'onderdeel.af': '{done} από {total} μέρη ολοκληρωμένα',
  'leerdoel.aantal.een': '1 στόχος',
  'leerdoel.aantal.meer': '{aantal} στόχοι',
  'rubriek.onderdelen': 'Μέρη',
  'rubriek.voortgang': 'Πρόοδος',
  'rubriek.introductie': 'Εισαγωγή',
  'rubriek.voorkennis': 'Προαπαιτούμενα',
  'rubriek.paragrafen': 'Παράγραφοι',
  'rubriek.oefentoetsen': 'Δοκιμαστικά τεστ',
  'rubriek.toetsen': 'Τεστ',
  'hoofdstuk.waarover': 'Για τι μιλάει αυτό το κεφάλαιο',
  'knop.opnieuwBekijken': 'Δες το ξανά',
  'knop.toonMinder': 'Δείξε λιγότερα',
  'knop.toonAlles': 'Δείξε όλα ({aantal})',
  'knop.toonAllesPlus': 'Δείξε όλα ({aantal}) - και τις προαιρετικές παραγράφους',
  'knop.startOnderdeel': 'Ξεκίνα αυτό το μέρος',
  'knop.beginBijStap1': 'Ξεκίνα από το βήμα 1',
  'knop.kopieerLink': 'Αντίγραψε τον σύνδεσμο',
  'knop.meerOpties': 'Περισσότερες επιλογές',
  'knop.terugNaarOverzicht': 'Πίσω στην επισκόπηση',
  'status.af': 'ολοκληρωμένα',
  'paragraaf.geenOnderdelen': 'Ο καθηγητής σου δεν έχει ετοιμάσει ακόμα μέρη για αυτή την παράγραφο.',
  'hoofdstuk.laden': 'Φόρτωση κεφαλαίου',
  'hoofdstuk.nietVoorJou.titel': 'Αυτό το κεφάλαιο δεν είναι έτοιμο για σένα',
  'hoofdstuk.nietVoorJou.tekst': 'Ίσως ο σύνδεσμος είναι παλιός ή ο καθηγητής σου δεν μοιράστηκε ακόμα το κεφάλαιο.',
  'nogTeDoen.kop': 'Μένουν ακόμα',
  'nogTeDoen.klaar': 'Αυτό το κεφάλαιο ολοκληρώθηκε.',
  'nogTeDoen.rest': 'και ακόμα {aantal} άλλα',
  'melding.linkGekopieerd': 'Ο σύνδεσμος αντιγράφηκε.',
  'melding.kopierenMislukt': 'Η αντιγραφή δεν πέτυχε.',
  'melding.kopierenKanNiet': 'Η αντιγραφή δεν γίνεται σε αυτό το πρόγραμμα περιήγησης.',
  'rubriek.paragraaf': 'Παράγραφος',
  'les.kop': 'Μάθημα',
  'les.leerdoelen': 'Στόχοι',
  'les.inDitHoofdstuk': 'Σε αυτό το κεφάλαιο',
  'les.onderdeelVan': 'Μέρος {nummer} από {totaal}',
  'les.terugNaarHoofdstuk': 'Πίσω στο κεφάλαιο',
  'les.paragraafAfronden': 'Ολοκλήρωση παραγράφου',
  'les.volledigScherm': 'Πλήρης οθόνη',
  'status.afgerond': 'Ολοκληρώθηκε',
  'status.nogNietAf': 'Δεν ολοκληρώθηκε ακόμα',
  'knop.vorige': 'Προηγούμενο',
  'knop.volgendeStap': 'Επόμενο βήμα',
  'les.afronden': 'Ολοκλήρωση μαθήματος',
  'intro.watJeGaatLeren': 'Τι θα μάθεις:',
  'intro.stappen.een': '1 βήμα',
  'intro.stappen.meer': '{aantal} βήματα',
  'plus.label': 'Πλας - προαιρετικό',
  'plus.kort': 'Πλας',
  'plus.hoeftNiet': 'Δεν είναι υποχρεωτικό - μπορείς όμως',
  'plus.extraAf': 'Πλας: {done} από {total} επιπλέον ολοκληρωμένα',
  'plus.staatKlaar': 'Η επιπλέον ύλη σε περιμένει αν θέλεις κι άλλο',
  'plus.uitleg': 'Αυτή η παράγραφος είναι προαιρετική. Δεν μετράει για το κεφάλαιό σου και δεν χρειάζεται να '
    + 'την τελειώσεις για να συνεχίσεις. Καλή ιδέα αν θέλεις αργότερα να πας στο havo - και '
    + 'κερδίζεις κανονικά tokens.',
  'slot.label': 'Ακόμα κλειδωμένο',
  'slot.titel': 'Αυτό το κεφάλαιο είναι ακόμα κλειδωμένο',
  'slot.uitleg': 'Ο καθηγητής σου θα το ανοίξει όταν ξεκινήσει το μάθημα.',
  'slot.komtEraan': 'Τα μαθήματα αυτού του κεφαλαίου έρχονται σύντομα.',
  'tijd.minuten': '{aantal} λεπτά',
  'tijd.uren': '{uren} ώρες',
  'tijd.urenMinuten': '{uren} ώρες {minuten} λεπτά',
  'profiel.taal.kop': 'Η γλώσσα των μαθημάτων σου',
  'profiel.taal.uitleg': 'Διάλεξε σε ποια γλώσσα θέλεις να διαβάζεις την εξήγηση. Τις απαντήσεις σου τις γράφεις στα ολλανδικά.',
  'profiel.taal.nederlands': 'Μόνο ολλανδικά',
  'profiel.taal.opgeslagen': 'Αποθηκεύτηκε.',
  'profiel.taal.mislukt': 'Η αποθήκευση δεν πέτυχε. Δοκίμασε ξανά σε λίγο.'
};

const IT = {
  'lesstof.kop': 'Lezioni',
  'lesstof.titel': 'Le tue lezioni',
  'lesstof.laden': 'Caricamento delle lezioni',
  'lesstof.leeg.titel': 'Non c’è ancora materiale per la tua classe',
  'lesstof.leeg.tekst': 'Il tuo insegnante metterà presto delle lezioni qui.',
  'verder.kop': 'Riprendi da dove eri',
  'verder.klaar.titel': 'Sei in pari',
  'verder.klaar.tekst': 'Hai finito tutto quello che era pronto. Scegli un capitolo qui sotto per rileggerlo.',
  'status.nietBegonnen': 'non ancora iniziato',
  'knop.beginnen': 'Inizia',
  'knop.gaVerder': 'Continua',
  'knop.openen': 'Apri',
  'knop.bekijkTerug': 'Rivedi',
  'knop.verder': 'Avanti',
  'knop.start': 'Inizia',
  'knop.opnieuw': 'Di nuovo',
  'hoofdstuk.kop': 'Capitolo',
  'hoofdstuk.kopMetNummer': 'Capitolo {nummer}',
  'hoofdstuk.af': 'Questo capitolo è completato',
  'hoofdstuk.aantal.een': '1 capitolo',
  'hoofdstuk.aantal.meer': '{aantal} capitoli',
  'paragraaf.aantal.een': '1 paragrafo',
  'paragraaf.aantal.meer': '{aantal} paragrafi',
  'onderdeel.aantal.een': '1 parte',
  'onderdeel.aantal.meer': '{aantal} parti',
  'onderdeel.geen': 'Ancora nessuna parte pubblicata',
  'onderdeel.af': '{done} di {total} parti completate',
  'leerdoel.aantal.een': '1 obiettivo',
  'leerdoel.aantal.meer': '{aantal} obiettivi',
  'rubriek.onderdelen': 'Parti',
  'rubriek.voortgang': 'Progresso',
  'rubriek.introductie': 'Introduzione',
  'rubriek.voorkennis': 'Conoscenze di base',
  'rubriek.paragrafen': 'Paragrafi',
  'rubriek.oefentoetsen': 'Test di esercitazione',
  'rubriek.toetsen': 'Verifiche',
  'hoofdstuk.waarover': 'Di che cosa parla questo capitolo',
  'knop.opnieuwBekijken': 'Rivedi',
  'knop.toonMinder': 'Mostra meno',
  'knop.toonAlles': 'Mostra tutto ({aantal})',
  'knop.toonAllesPlus': 'Mostra tutto ({aantal}) - anche i paragrafi facoltativi',
  'knop.startOnderdeel': 'Inizia questa parte',
  'knop.beginBijStap1': 'Inizia dal passaggio 1',
  'knop.kopieerLink': 'Copia il link',
  'knop.meerOpties': 'Altre opzioni',
  'knop.terugNaarOverzicht': 'Torna alla panoramica',
  'status.af': 'completate',
  'paragraaf.geenOnderdelen': 'Il tuo insegnante non ha ancora preparato delle parti per questo paragrafo.',
  'hoofdstuk.laden': 'Caricamento del capitolo',
  'hoofdstuk.nietVoorJou.titel': 'Questo capitolo non è pronto per te',
  'hoofdstuk.nietVoorJou.tekst': 'Forse il link è vecchio, oppure il tuo insegnante non ha ancora condiviso il capitolo.',
  'nogTeDoen.kop': 'Ancora da fare',
  'nogTeDoen.klaar': 'Questo capitolo è completato.',
  'nogTeDoen.rest': 'e altri {aantal}',
  'melding.linkGekopieerd': 'Link copiato.',
  'melding.kopierenMislukt': 'La copia non è riuscita.',
  'melding.kopierenKanNiet': 'La copia non funziona in questo browser.',
  'rubriek.paragraaf': 'Paragrafo',
  'les.kop': 'Lezione',
  'les.leerdoelen': 'Obiettivi',
  'les.inDitHoofdstuk': 'In questo capitolo',
  'les.onderdeelVan': 'Parte {nummer} di {totaal}',
  'les.terugNaarHoofdstuk': 'Torna al capitolo',
  'les.paragraafAfronden': 'Completa il paragrafo',
  'les.volledigScherm': 'Schermo intero',
  'status.afgerond': 'Completato',
  'status.nogNietAf': 'Non ancora completato',
  'knop.vorige': 'Precedente',
  'knop.volgendeStap': 'Passaggio successivo',
  'les.afronden': 'Completa la lezione',
  'intro.watJeGaatLeren': 'Che cosa imparerai:',
  'intro.stappen.een': '1 passaggio',
  'intro.stappen.meer': '{aantal} passaggi',
  'plus.label': 'Plus - facoltativo',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'Non è obbligatorio - ma puoi farlo',
  'plus.extraAf': 'Plus: {done} di {total} extra completati',
  'plus.staatKlaar': 'Il materiale extra è pronto se vuoi fare di più',
  'plus.uitleg': 'Questo paragrafo è facoltativo. Non conta per il tuo capitolo e non devi finirlo per '
    + 'andare avanti. È consigliato se più avanti vuoi passare all’havo - e in più guadagni dei token.',
  'slot.label': 'Ancora bloccato',
  'slot.titel': 'Questo capitolo è ancora bloccato',
  'slot.uitleg': 'Il tuo insegnante lo aprirà quando inizia la lezione.',
  'slot.komtEraan': 'Le lezioni di questo capitolo arrivano presto.',
  'tijd.minuten': '{aantal} min',
  'tijd.uren': '{uren} ore',
  'tijd.urenMinuten': '{uren} ore {minuten} min',
  'profiel.taal.kop': 'La lingua delle tue lezioni',
  'profiel.taal.uitleg': 'Scegli in quale lingua vuoi leggere le spiegazioni. Le risposte le scrivi in olandese.',
  'profiel.taal.nederlands': 'Solo olandese',
  'profiel.taal.opgeslagen': 'Salvato.',
  'profiel.taal.mislukt': 'Il salvataggio non è riuscito. Riprova tra poco.'
};

const UK = {
  'lesstof.kop': 'Уроки',
  'lesstof.titel': 'Твої уроки',
  'lesstof.laden': 'Завантаження уроків',
  'lesstof.leeg.titel': 'Для твого класу ще немає матеріалу',
  'lesstof.leeg.tekst': 'Твій учитель скоро додасть сюди уроки.',
  'verder.kop': 'Продовж із того місця, де зупинився',
  'verder.klaar.titel': 'Ти все зробив',
  'verder.klaar.tekst': 'Ти закінчив усе, що було готове. Обери розділ нижче, щоб щось перечитати.',
  'status.nietBegonnen': 'ще не розпочато',
  'knop.beginnen': 'Почати',
  'knop.gaVerder': 'Продовжити',
  'knop.openen': 'Відкрити',
  'knop.bekijkTerug': 'Переглянути ще раз',
  'knop.verder': 'Далі',
  'knop.start': 'Почати',
  'knop.opnieuw': 'Ще раз',
  'hoofdstuk.kop': 'Розділ',
  'hoofdstuk.kopMetNummer': 'Розділ {nummer}',
  'hoofdstuk.af': 'Цей розділ завершено',
  'hoofdstuk.aantal.een': '1 розділ',
  'hoofdstuk.aantal.meer': 'Розділів: {aantal}',
  'paragraaf.aantal.een': '1 параграф',
  'paragraaf.aantal.meer': 'Параграфів: {aantal}',
  'onderdeel.aantal.een': '1 частина',
  'onderdeel.aantal.meer': 'Частин: {aantal}',
  'onderdeel.geen': 'Ще немає опублікованих частин',
  'onderdeel.af': 'Виконано {done} з {total} частин',
  'leerdoel.aantal.een': '1 мета',
  'leerdoel.aantal.meer': 'Цілей: {aantal}',
  'rubriek.onderdelen': 'Частини',
  'rubriek.voortgang': 'Прогрес',
  'rubriek.introductie': 'Вступ',
  'rubriek.voorkennis': 'Базові знання',
  'rubriek.paragrafen': 'Параграфи',
  'rubriek.oefentoetsen': 'Тренувальні тести',
  'rubriek.toetsen': 'Тести',
  'hoofdstuk.waarover': 'Про що цей розділ',
  'knop.opnieuwBekijken': 'Переглянути ще раз',
  'knop.toonMinder': 'Показати менше',
  'knop.toonAlles': 'Показати все ({aantal})',
  'knop.toonAllesPlus': 'Показати все ({aantal}) - також додаткові параграфи',
  'knop.startOnderdeel': 'Почати цю частину',
  'knop.beginBijStap1': 'Почати з кроку 1',
  'knop.kopieerLink': 'Скопіювати посилання',
  'knop.meerOpties': 'Інші дії',
  'knop.terugNaarOverzicht': 'Назад до огляду',
  'status.af': 'виконано',
  'paragraaf.geenOnderdelen': 'Твій учитель ще не підготував частини для цього параграфа.',
  'hoofdstuk.laden': 'Завантаження розділу',
  'hoofdstuk.nietVoorJou.titel': 'Цей розділ для тебе ще не готовий',
  'hoofdstuk.nietVoorJou.tekst': 'Можливо, посилання старе або вчитель ще не поділився розділом.',
  'nogTeDoen.kop': 'Ще треба зробити',
  'nogTeDoen.klaar': 'Цей розділ завершено.',
  'nogTeDoen.rest': 'і ще {aantal}',
  'melding.linkGekopieerd': 'Посилання скопійовано.',
  'melding.kopierenMislukt': 'Скопіювати не вдалося.',
  'melding.kopierenKanNiet': 'У цьому браузері копіювання не працює.',
  'rubriek.paragraaf': 'Параграф',
  'les.kop': 'Урок',
  'les.leerdoelen': 'Цілі',
  'les.inDitHoofdstuk': 'У цьому розділі',
  'les.onderdeelVan': 'Частина {nummer} з {totaal}',
  'les.terugNaarHoofdstuk': 'Назад до розділу',
  'les.paragraafAfronden': 'Завершити параграф',
  'les.volledigScherm': 'На весь екран',
  'status.afgerond': 'Виконано',
  'status.nogNietAf': 'Ще не виконано',
  'knop.vorige': 'Назад',
  'knop.volgendeStap': 'Наступний крок',
  'les.afronden': 'Завершити урок',
  'intro.watJeGaatLeren': 'Що ти вивчиш:',
  'intro.stappen.een': '1 крок',
  'intro.stappen.meer': 'Кроків: {aantal}',
  'plus.label': 'Плюс - за бажанням',
  'plus.kort': 'Плюс',
  'plus.hoeftNiet': 'Не обов’язково - але можна',
  'plus.extraAf': 'Плюс: виконано {done} з {total} додаткових',
  'plus.staatKlaar': 'Додатковий матеріал чекає, якщо хочеш більше',
  'plus.uitleg': 'Цей параграф необов’язковий. Він не зараховується до розділу, і тобі не треба його '
    + 'закінчувати, щоб іти далі. Це гарна ідея, якщо пізніше хочеш перейти в havo - і ти все одно '
    + 'заробляєш токени.',
  'slot.label': 'Ще закрито',
  'slot.titel': 'Цей розділ ще закритий',
  'slot.uitleg': 'Учитель відкриє його, коли почнеться урок.',
  'slot.komtEraan': 'Уроки цього розділу скоро з’являться.',
  'tijd.minuten': '{aantal} хв',
  'tijd.uren': '{uren} год',
  'tijd.urenMinuten': '{uren} год {minuten} хв',
  'profiel.taal.kop': 'Мова твоїх уроків',
  'profiel.taal.uitleg': 'Обери мову, якою хочеш читати пояснення. Відповіді ти пишеш нідерландською.',
  'profiel.taal.nederlands': 'Тільки нідерландська',
  'profiel.taal.opgeslagen': 'Збережено.',
  'profiel.taal.mislukt': 'Не вдалося зберегти. Спробуй ще раз трохи згодом.'
};

const EN = {
  'lesstof.kop': 'Lessons',
  'lesstof.titel': 'Your lessons',
  'lesstof.laden': 'Loading lessons',
  'lesstof.leeg.titel': 'No lessons ready for your class yet',
  'lesstof.leeg.tekst': 'Your teacher will put lessons here soon.',
  'verder.kop': 'Carry on where you left off',
  'verder.klaar.titel': 'You are up to date',
  'verder.klaar.tekst': 'You have finished everything that was ready. Pick a chapter below to read something again.',
  'status.nietBegonnen': 'not started yet',
  'knop.beginnen': 'Start',
  'knop.gaVerder': 'Continue',
  'knop.openen': 'Open',
  'knop.bekijkTerug': 'Look back',
  'knop.verder': 'Next',
  'knop.start': 'Start',
  'knop.opnieuw': 'Again',
  'hoofdstuk.kop': 'Chapter',
  'hoofdstuk.kopMetNummer': 'Chapter {nummer}',
  'hoofdstuk.af': 'This chapter is finished',
  'hoofdstuk.aantal.een': '1 chapter',
  'hoofdstuk.aantal.meer': '{aantal} chapters',
  'paragraaf.aantal.een': '1 section',
  'paragraaf.aantal.meer': '{aantal} sections',
  'onderdeel.aantal.een': '1 part',
  'onderdeel.aantal.meer': '{aantal} parts',
  'onderdeel.geen': 'No published parts yet',
  'onderdeel.af': '{done} of {total} parts done',
  'leerdoel.aantal.een': '1 learning goal',
  'leerdoel.aantal.meer': '{aantal} learning goals',
  'rubriek.onderdelen': 'Parts',
  'rubriek.voortgang': 'Progress',
  'rubriek.introductie': 'Introduction',
  'rubriek.voorkennis': 'Prior knowledge',
  'rubriek.paragrafen': 'Sections',
  'rubriek.oefentoetsen': 'Practice tests',
  'rubriek.toetsen': 'Tests',
  'hoofdstuk.waarover': 'What this chapter is about',
  'knop.opnieuwBekijken': 'Look again',
  'knop.toonMinder': 'Show less',
  'knop.toonAlles': 'Show all ({aantal})',
  'knop.toonAllesPlus': 'Show all ({aantal}) - including the plus sections',
  'knop.startOnderdeel': 'Start this part',
  'knop.beginBijStap1': 'Start at step 1',
  'knop.kopieerLink': 'Copy link',
  'knop.meerOpties': 'More options',
  'knop.terugNaarOverzicht': 'Back to overview',
  'status.af': 'done',
  'paragraaf.geenOnderdelen': 'Your teacher has not prepared any parts for this section yet.',
  'hoofdstuk.laden': 'Loading chapter',
  'hoofdstuk.nietVoorJou.titel': 'This chapter is not ready for you',
  'hoofdstuk.nietVoorJou.tekst': 'The link may be old, or your teacher has not shared the chapter yet.',
  'nogTeDoen.kop': 'Still to do',
  'nogTeDoen.klaar': 'This chapter is finished.',
  'nogTeDoen.rest': 'and {aantal} more',
  'melding.linkGekopieerd': 'Link copied.',
  'melding.kopierenMislukt': 'Copying did not work.',
  'melding.kopierenKanNiet': 'Copying does not work in this browser.',
  'rubriek.paragraaf': 'Section',
  'les.kop': 'Lesson',
  'les.leerdoelen': 'Learning goals',
  'les.inDitHoofdstuk': 'In this chapter',
  'les.onderdeelVan': 'Part {nummer} of {totaal}',
  'les.terugNaarHoofdstuk': 'Back to the chapter',
  'les.paragraafAfronden': 'Finish section',
  'les.volledigScherm': 'Full screen',
  'status.afgerond': 'Done',
  'status.nogNietAf': 'Not done yet',
  'knop.vorige': 'Previous',
  'knop.volgendeStap': 'Next step',
  'les.afronden': 'Finish lesson',
  'intro.watJeGaatLeren': 'What you will learn:',
  'intro.stappen.een': '1 step',
  'intro.stappen.meer': '{aantal} steps',
  'plus.label': 'Plus - optional',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'Not required - but you may',
  'plus.extraAf': 'Plus: {done} of {total} extra done',
  'plus.staatKlaar': 'Extra material is ready if you want more',
  'plus.uitleg': 'This section is optional. It does not count towards your chapter and you do not have to '
    + 'finish it to move on. Worth doing if you want to go to havo later - and you still earn tokens.',
  'slot.label': 'Still locked',
  'slot.titel': 'This chapter is still locked',
  'slot.uitleg': 'Your teacher will open it when the lesson starts.',
  'slot.komtEraan': 'The lessons for this chapter are coming soon.',
  'tijd.minuten': '{aantal} min',
  'tijd.uren': '{uren} h',
  'tijd.urenMinuten': '{uren} h {minuten} min',
  'profiel.taal.kop': 'The language of your lessons',
  'profiel.taal.uitleg': 'Choose the language you want to read the explanations in. You write your answers in Dutch.',
  'profiel.taal.nederlands': 'Dutch only',
  'profiel.taal.opgeslagen': 'Saved.',
  'profiel.taal.mislukt': 'Saving did not work. Please try again in a moment.'
};

const TR = {
  'lesstof.kop': 'Dersler',
  'lesstof.titel': 'Derslerin',
  'lesstof.laden': 'Dersler yükleniyor',
  'lesstof.leeg.titel': 'Sınıfın için henüz ders hazır değil',
  'lesstof.leeg.tekst': 'Öğretmenin yakında buraya dersler koyacak.',
  'verder.kop': 'Kaldığın yerden devam et',
  'verder.klaar.titel': 'Güncelsin',
  'verder.klaar.tekst': 'Hazır olan her şeyi bitirdin. Bir şeyi tekrar okumak için aşağıdan bir bölüm seç.',
  'status.nietBegonnen': 'henüz başlamadın',
  'knop.beginnen': 'Başla',
  'knop.gaVerder': 'Devam et',
  'knop.openen': 'Aç',
  'knop.bekijkTerug': 'Tekrar bak',
  'knop.verder': 'İleri',
  'knop.start': 'Başla',
  'knop.opnieuw': 'Tekrar',
  'hoofdstuk.kop': 'Bölüm',
  'hoofdstuk.kopMetNummer': 'Bölüm {nummer}',
  'hoofdstuk.af': 'Bu bölüm tamamlandı',
  'hoofdstuk.aantal.een': '1 bölüm',
  'hoofdstuk.aantal.meer': '{aantal} bölüm',
  'paragraaf.aantal.een': '1 paragraf',
  'paragraaf.aantal.meer': '{aantal} paragraf',
  'onderdeel.aantal.een': '1 parça',
  'onderdeel.aantal.meer': '{aantal} parça',
  'onderdeel.geen': 'Henüz yayınlanmış parça yok',
  'onderdeel.af': '{total} parçanın {done} tanesi bitti',
  'leerdoel.aantal.een': '1 hedef',
  'leerdoel.aantal.meer': '{aantal} hedef',
  'rubriek.onderdelen': 'Parçalar',
  'rubriek.voortgang': 'İlerleme',
  'rubriek.introductie': 'Giriş',
  'rubriek.voorkennis': 'Ön bilgi',
  'rubriek.paragrafen': 'Paragraflar',
  'rubriek.oefentoetsen': 'Alıştırma testleri',
  'rubriek.toetsen': 'Sınavlar',
  'hoofdstuk.waarover': 'Bu bölüm neyle ilgili',
  'knop.opnieuwBekijken': 'Tekrar bak',
  'knop.toonMinder': 'Daha az göster',
  'knop.toonAlles': 'Hepsini göster ({aantal})',
  'knop.toonAllesPlus': 'Hepsini göster ({aantal}) - artı paragraflar dahil',
  'knop.startOnderdeel': 'Bu parçaya başla',
  'knop.beginBijStap1': '1. adımdan başla',
  'knop.kopieerLink': 'Bağlantıyı kopyala',
  'knop.meerOpties': 'Diğer seçenekler',
  'knop.terugNaarOverzicht': 'Genel bakışa dön',
  'status.af': 'bitti',
  'paragraaf.geenOnderdelen': 'Öğretmenin bu paragraf için henüz parça hazırlamadı.',
  'hoofdstuk.laden': 'Bölüm yükleniyor',
  'hoofdstuk.nietVoorJou.titel': 'Bu bölüm senin için hazır değil',
  'hoofdstuk.nietVoorJou.tekst': 'Bağlantı eski olabilir ya da öğretmenin bölümü henüz paylaşmamış olabilir.',
  'nogTeDoen.kop': 'Yapılacaklar',
  'nogTeDoen.klaar': 'Bu bölüm tamamlandı.',
  'nogTeDoen.rest': 've {aantal} tane daha',
  'melding.linkGekopieerd': 'Bağlantı kopyalandı.',
  'melding.kopierenMislukt': 'Kopyalama olmadı.',
  'melding.kopierenKanNiet': 'Bu tarayıcıda kopyalama çalışmıyor.',
  'rubriek.paragraaf': 'Paragraf',
  'les.kop': 'Ders',
  'les.leerdoelen': 'Hedefler',
  'les.inDitHoofdstuk': 'Bu bölümde',
  'les.onderdeelVan': '{totaal} parçadan {nummer}. parça',
  'les.terugNaarHoofdstuk': 'Bölüme dön',
  'les.paragraafAfronden': 'Paragrafı bitir',
  'les.volledigScherm': 'Tam ekran',
  'status.afgerond': 'Bitti',
  'status.nogNietAf': 'Henüz bitmedi',
  'knop.vorige': 'Önceki',
  'knop.volgendeStap': 'Sonraki adım',
  'les.afronden': 'Dersi bitir',
  'intro.watJeGaatLeren': 'Ne öğreneceksin:',
  'intro.stappen.een': '1 adım',
  'intro.stappen.meer': '{aantal} adım',
  'plus.label': 'Plus - isteğe bağlı',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'Zorunlu değil - istersen yapabilirsin',
  'plus.extraAf': 'Plus: {total} ekstradan {done} tanesi bitti',
  'plus.staatKlaar': 'Daha fazlasını istersen ekstra materyal hazır',
  'plus.uitleg': 'Bu paragraf isteğe bağlı. Bölümün için sayılmaz ve devam etmek için bitirmen gerekmez. '
    + 'İleride havo’ya geçmek istersen iyi olur - ve yine de token kazanırsın.',
  'slot.label': 'Hâlâ kilitli',
  'slot.titel': 'Bu bölüm hâlâ kilitli',
  'slot.uitleg': 'Öğretmenin ders başlayınca açacak.',
  'slot.komtEraan': 'Bu bölümün dersleri yakında geliyor.',
  'tijd.minuten': '{aantal} dk',
  'tijd.uren': '{uren} saat',
  'tijd.urenMinuten': '{uren} saat {minuten} dk',
  'profiel.taal.kop': 'Derslerinin dili',
  'profiel.taal.uitleg': 'Açıklamaları hangi dilde okumak istediğini seç. Cevaplarını Felemenkçe yazarsın.',
  'profiel.taal.nederlands': 'Sadece Felemenkçe',
  'profiel.taal.opgeslagen': 'Kaydedildi.',
  'profiel.taal.mislukt': 'Kaydetme olmadı. Birazdan tekrar dene.'
};

const PL = {
  'lesstof.kop': 'Lekcje',
  'lesstof.titel': 'Twoje lekcje',
  'lesstof.laden': 'Wczytywanie lekcji',
  'lesstof.leeg.titel': 'Dla twojej klasy nie ma jeszcze materiału',
  'lesstof.leeg.tekst': 'Nauczyciel wkrótce doda tu lekcje.',
  'verder.kop': 'Kontynuuj tam, gdzie skończyłeś',
  'verder.klaar.titel': 'Jesteś na bieżąco',
  'verder.klaar.tekst': 'Skończyłeś wszystko, co było gotowe. Wybierz niżej rozdział, żeby coś powtórzyć.',
  'status.nietBegonnen': 'jeszcze nie zaczęte',
  'knop.beginnen': 'Zacznij',
  'knop.gaVerder': 'Kontynuuj',
  'knop.openen': 'Otwórz',
  'knop.bekijkTerug': 'Obejrzyj ponownie',
  'knop.verder': 'Dalej',
  'knop.start': 'Zacznij',
  'knop.opnieuw': 'Jeszcze raz',
  'hoofdstuk.kop': 'Rozdział',
  'hoofdstuk.kopMetNummer': 'Rozdział {nummer}',
  'hoofdstuk.af': 'Ten rozdział jest skończony',
  'hoofdstuk.aantal.een': '1 rozdział',
  'hoofdstuk.aantal.meer': 'Rozdziały: {aantal}',
  'paragraaf.aantal.een': '1 paragraf',
  'paragraaf.aantal.meer': 'Paragrafy: {aantal}',
  'onderdeel.aantal.een': '1 część',
  'onderdeel.aantal.meer': 'Części: {aantal}',
  'onderdeel.geen': 'Nie ma jeszcze opublikowanych części',
  'onderdeel.af': 'Skończone {done} z {total} części',
  'leerdoel.aantal.een': '1 cel',
  'leerdoel.aantal.meer': 'Cele: {aantal}',
  'rubriek.onderdelen': 'Części',
  'rubriek.voortgang': 'Postęp',
  'rubriek.introductie': 'Wprowadzenie',
  'rubriek.voorkennis': 'Wiedza wstępna',
  'rubriek.paragrafen': 'Paragrafy',
  'rubriek.oefentoetsen': 'Testy ćwiczeniowe',
  'rubriek.toetsen': 'Sprawdziany',
  'hoofdstuk.waarover': 'O czym jest ten rozdział',
  'knop.opnieuwBekijken': 'Obejrzyj ponownie',
  'knop.toonMinder': 'Pokaż mniej',
  'knop.toonAlles': 'Pokaż wszystko ({aantal})',
  'knop.toonAllesPlus': 'Pokaż wszystko ({aantal}) - także paragrafy plus',
  'knop.startOnderdeel': 'Zacznij tę część',
  'knop.beginBijStap1': 'Zacznij od kroku 1',
  'knop.kopieerLink': 'Skopiuj link',
  'knop.meerOpties': 'Więcej opcji',
  'knop.terugNaarOverzicht': 'Wróć do przeglądu',
  'status.af': 'skończone',
  'paragraaf.geenOnderdelen': 'Nauczyciel nie przygotował jeszcze części do tego paragrafu.',
  'hoofdstuk.laden': 'Wczytywanie rozdziału',
  'hoofdstuk.nietVoorJou.titel': 'Ten rozdział nie jest dla ciebie gotowy',
  'hoofdstuk.nietVoorJou.tekst': 'Może link jest stary albo nauczyciel jeszcze nie udostępnił rozdziału.',
  'nogTeDoen.kop': 'Do zrobienia',
  'nogTeDoen.klaar': 'Ten rozdział jest skończony.',
  'nogTeDoen.rest': 'i jeszcze {aantal}',
  'melding.linkGekopieerd': 'Link skopiowany.',
  'melding.kopierenMislukt': 'Kopiowanie się nie udało.',
  'melding.kopierenKanNiet': 'W tej przeglądarce kopiowanie nie działa.',
  'rubriek.paragraaf': 'Paragraf',
  'les.kop': 'Lekcja',
  'les.leerdoelen': 'Cele',
  'les.inDitHoofdstuk': 'W tym rozdziale',
  'les.onderdeelVan': 'Część {nummer} z {totaal}',
  'les.terugNaarHoofdstuk': 'Wróć do rozdziału',
  'les.paragraafAfronden': 'Zakończ paragraf',
  'les.volledigScherm': 'Pełny ekran',
  'status.afgerond': 'Skończone',
  'status.nogNietAf': 'Jeszcze nieskończone',
  'knop.vorige': 'Poprzedni',
  'knop.volgendeStap': 'Następny krok',
  'les.afronden': 'Zakończ lekcję',
  'intro.watJeGaatLeren': 'Czego się nauczysz:',
  'intro.stappen.een': '1 krok',
  'intro.stappen.meer': 'Kroki: {aantal}',
  'plus.label': 'Plus - nieobowiązkowe',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'Nie musisz - ale możesz',
  'plus.extraAf': 'Plus: skończone {done} z {total} dodatkowych',
  'plus.staatKlaar': 'Materiał dodatkowy czeka, jeśli chcesz więcej',
  'plus.uitleg': 'Ten paragraf jest nieobowiązkowy. Nie liczy się do rozdziału i nie musisz go kończyć, '
    + 'żeby iść dalej. Warto, jeśli później chcesz przejść do havo - a i tak zdobywasz tokeny.',
  'slot.label': 'Jeszcze zamknięte',
  'slot.titel': 'Ten rozdział jest jeszcze zamknięty',
  'slot.uitleg': 'Nauczyciel otworzy go, gdy zacznie się lekcja.',
  'slot.komtEraan': 'Lekcje z tego rozdziału już wkrótce.',
  'tijd.minuten': '{aantal} min',
  'tijd.uren': '{uren} godz.',
  'tijd.urenMinuten': '{uren} godz. {minuten} min',
  'profiel.taal.kop': 'Język twoich lekcji',
  'profiel.taal.uitleg': 'Wybierz język, w którym chcesz czytać wyjaśnienia. Odpowiedzi piszesz po niderlandzku.',
  'profiel.taal.nederlands': 'Tylko niderlandzki',
  'profiel.taal.opgeslagen': 'Zapisano.',
  'profiel.taal.mislukt': 'Zapis się nie udał. Spróbuj za chwilę jeszcze raz.'
};

const RO = {
  'lesstof.kop': 'Lecții',
  'lesstof.titel': 'Lecțiile tale',
  'lesstof.laden': 'Se încarcă lecțiile',
  'lesstof.leeg.titel': 'Încă nu există material pentru clasa ta',
  'lesstof.leeg.tekst': 'Profesorul tău va pune aici lecții în curând.',
  'verder.kop': 'Continuă de unde ai rămas',
  'verder.klaar.titel': 'Ești la zi',
  'verder.klaar.tekst': 'Ai terminat tot ce era gata. Alege un capitol mai jos ca să recitești ceva.',
  'status.nietBegonnen': 'încă neînceput',
  'knop.beginnen': 'Începe',
  'knop.gaVerder': 'Continuă',
  'knop.openen': 'Deschide',
  'knop.bekijkTerug': 'Revezi',
  'knop.verder': 'Mai departe',
  'knop.start': 'Începe',
  'knop.opnieuw': 'Din nou',
  'hoofdstuk.kop': 'Capitol',
  'hoofdstuk.kopMetNummer': 'Capitolul {nummer}',
  'hoofdstuk.af': 'Acest capitol este terminat',
  'hoofdstuk.aantal.een': '1 capitol',
  'hoofdstuk.aantal.meer': '{aantal} capitole',
  'paragraaf.aantal.een': '1 paragraf',
  'paragraaf.aantal.meer': '{aantal} paragrafe',
  'onderdeel.aantal.een': '1 parte',
  'onderdeel.aantal.meer': '{aantal} părți',
  'onderdeel.geen': 'Încă nu sunt părți publicate',
  'onderdeel.af': '{done} din {total} părți terminate',
  'leerdoel.aantal.een': '1 obiectiv',
  'leerdoel.aantal.meer': '{aantal} obiective',
  'rubriek.onderdelen': 'Părți',
  'rubriek.voortgang': 'Progres',
  'rubriek.introductie': 'Introducere',
  'rubriek.voorkennis': 'Cunoștințe de bază',
  'rubriek.paragrafen': 'Paragrafe',
  'rubriek.oefentoetsen': 'Teste de exercițiu',
  'rubriek.toetsen': 'Teste',
  'hoofdstuk.waarover': 'Despre ce este acest capitol',
  'knop.opnieuwBekijken': 'Revezi',
  'knop.toonMinder': 'Arată mai puțin',
  'knop.toonAlles': 'Arată tot ({aantal})',
  'knop.toonAllesPlus': 'Arată tot ({aantal}) - și paragrafele plus',
  'knop.startOnderdeel': 'Începe această parte',
  'knop.beginBijStap1': 'Începe de la pasul 1',
  'knop.kopieerLink': 'Copiază linkul',
  'knop.meerOpties': 'Mai multe opțiuni',
  'knop.terugNaarOverzicht': 'Înapoi la prezentare',
  'status.af': 'terminate',
  'paragraaf.geenOnderdelen': 'Profesorul tău nu a pregătit încă părți pentru acest paragraf.',
  'hoofdstuk.laden': 'Se încarcă capitolul',
  'hoofdstuk.nietVoorJou.titel': 'Acest capitol nu este pregătit pentru tine',
  'hoofdstuk.nietVoorJou.tekst': 'Poate linkul este vechi sau profesorul nu a împărțit încă capitolul.',
  'nogTeDoen.kop': 'De făcut',
  'nogTeDoen.klaar': 'Acest capitol este terminat.',
  'nogTeDoen.rest': 'și încă {aantal}',
  'melding.linkGekopieerd': 'Link copiat.',
  'melding.kopierenMislukt': 'Copierea nu a reușit.',
  'melding.kopierenKanNiet': 'Copierea nu funcționează în acest browser.',
  'rubriek.paragraaf': 'Paragraf',
  'les.kop': 'Lecție',
  'les.leerdoelen': 'Obiective',
  'les.inDitHoofdstuk': 'În acest capitol',
  'les.onderdeelVan': 'Partea {nummer} din {totaal}',
  'les.terugNaarHoofdstuk': 'Înapoi la capitol',
  'les.paragraafAfronden': 'Termină paragraful',
  'les.volledigScherm': 'Ecran complet',
  'status.afgerond': 'Terminat',
  'status.nogNietAf': 'Încă neterminat',
  'knop.vorige': 'Anterior',
  'knop.volgendeStap': 'Pasul următor',
  'les.afronden': 'Termină lecția',
  'intro.watJeGaatLeren': 'Ce vei învăța:',
  'intro.stappen.een': '1 pas',
  'intro.stappen.meer': '{aantal} pași',
  'plus.label': 'Plus - opțional',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'Nu este obligatoriu - dar poți',
  'plus.extraAf': 'Plus: {done} din {total} suplimentare terminate',
  'plus.staatKlaar': 'Materialul suplimentar te așteaptă dacă vrei mai mult',
  'plus.uitleg': 'Acest paragraf este opțional. Nu contează pentru capitolul tău și nu trebuie să îl '
    + 'termini ca să mergi mai departe. Este bun dacă mai târziu vrei să treci la havo - și oricum '
    + 'câștigi tokenuri.',
  'slot.label': 'Încă blocat',
  'slot.titel': 'Acest capitol este încă blocat',
  'slot.uitleg': 'Profesorul îl va deschide când începe lecția.',
  'slot.komtEraan': 'Lecțiile acestui capitol vin în curând.',
  'tijd.minuten': '{aantal} min',
  'tijd.uren': '{uren} ore',
  'tijd.urenMinuten': '{uren} ore {minuten} min',
  'profiel.taal.kop': 'Limba lecțiilor tale',
  'profiel.taal.uitleg': 'Alege limba în care vrei să citești explicațiile. Răspunsurile le scrii în olandeză.',
  'profiel.taal.nederlands': 'Doar olandeză',
  'profiel.taal.opgeslagen': 'Salvat.',
  'profiel.taal.mislukt': 'Salvarea nu a reușit. Încearcă din nou peste puțin timp.'
};

const ES = {
  'lesstof.kop': 'Lecciones',
  'lesstof.titel': 'Tus lecciones',
  'lesstof.laden': 'Cargando lecciones',
  'lesstof.leeg.titel': 'Todavía no hay material para tu clase',
  'lesstof.leeg.tekst': 'Tu profesor pondrá lecciones aquí pronto.',
  'verder.kop': 'Sigue donde lo dejaste',
  'verder.klaar.titel': 'Estás al día',
  'verder.klaar.tekst': 'Has terminado todo lo que estaba listo. Elige un capítulo abajo para releer algo.',
  'status.nietBegonnen': 'aún sin empezar',
  'knop.beginnen': 'Empezar',
  'knop.gaVerder': 'Continuar',
  'knop.openen': 'Abrir',
  'knop.bekijkTerug': 'Volver a ver',
  'knop.verder': 'Siguiente',
  'knop.start': 'Empezar',
  'knop.opnieuw': 'Otra vez',
  'hoofdstuk.kop': 'Capítulo',
  'hoofdstuk.kopMetNummer': 'Capítulo {nummer}',
  'hoofdstuk.af': 'Este capítulo está terminado',
  'hoofdstuk.aantal.een': '1 capítulo',
  'hoofdstuk.aantal.meer': '{aantal} capítulos',
  'paragraaf.aantal.een': '1 apartado',
  'paragraaf.aantal.meer': '{aantal} apartados',
  'onderdeel.aantal.een': '1 parte',
  'onderdeel.aantal.meer': '{aantal} partes',
  'onderdeel.geen': 'Todavía no hay partes publicadas',
  'onderdeel.af': '{done} de {total} partes hechas',
  'leerdoel.aantal.een': '1 objetivo',
  'leerdoel.aantal.meer': '{aantal} objetivos',
  'rubriek.onderdelen': 'Partes',
  'rubriek.voortgang': 'Progreso',
  'rubriek.introductie': 'Introducción',
  'rubriek.voorkennis': 'Conocimientos previos',
  'rubriek.paragrafen': 'Apartados',
  'rubriek.oefentoetsen': 'Pruebas de práctica',
  'rubriek.toetsen': 'Exámenes',
  'hoofdstuk.waarover': 'De qué trata este capítulo',
  'knop.opnieuwBekijken': 'Volver a ver',
  'knop.toonMinder': 'Mostrar menos',
  'knop.toonAlles': 'Mostrar todo ({aantal})',
  'knop.toonAllesPlus': 'Mostrar todo ({aantal}) - también los apartados plus',
  'knop.startOnderdeel': 'Empezar esta parte',
  'knop.beginBijStap1': 'Empezar por el paso 1',
  'knop.kopieerLink': 'Copiar enlace',
  'knop.meerOpties': 'Más opciones',
  'knop.terugNaarOverzicht': 'Volver al resumen',
  'status.af': 'hechas',
  'paragraaf.geenOnderdelen': 'Tu profesor aún no ha preparado partes para este apartado.',
  'hoofdstuk.laden': 'Cargando capítulo',
  'hoofdstuk.nietVoorJou.titel': 'Este capítulo no está listo para ti',
  'hoofdstuk.nietVoorJou.tekst': 'Quizá el enlace es antiguo o tu profesor aún no ha compartido el capítulo.',
  'nogTeDoen.kop': 'Por hacer',
  'nogTeDoen.klaar': 'Este capítulo está terminado.',
  'nogTeDoen.rest': 'y {aantal} más',
  'melding.linkGekopieerd': 'Enlace copiado.',
  'melding.kopierenMislukt': 'No se pudo copiar.',
  'melding.kopierenKanNiet': 'Copiar no funciona en este navegador.',
  'rubriek.paragraaf': 'Apartado',
  'les.kop': 'Lección',
  'les.leerdoelen': 'Objetivos',
  'les.inDitHoofdstuk': 'En este capítulo',
  'les.onderdeelVan': 'Parte {nummer} de {totaal}',
  'les.terugNaarHoofdstuk': 'Volver al capítulo',
  'les.paragraafAfronden': 'Terminar el apartado',
  'les.volledigScherm': 'Pantalla completa',
  'status.afgerond': 'Hecho',
  'status.nogNietAf': 'Todavía sin terminar',
  'knop.vorige': 'Anterior',
  'knop.volgendeStap': 'Siguiente paso',
  'les.afronden': 'Terminar la lección',
  'intro.watJeGaatLeren': 'Lo que vas a aprender:',
  'intro.stappen.een': '1 paso',
  'intro.stappen.meer': '{aantal} pasos',
  'plus.label': 'Plus - voluntario',
  'plus.kort': 'Plus',
  'plus.hoeftNiet': 'No es obligatorio - pero puedes',
  'plus.extraAf': 'Plus: {done} de {total} extras hechos',
  'plus.staatKlaar': 'El material extra está listo si quieres más',
  'plus.uitleg': 'Este apartado es voluntario. No cuenta para tu capítulo y no tienes que terminarlo para '
    + 'seguir. Es recomendable si más adelante quieres pasar al havo - y además ganas tokens.',
  'slot.label': 'Aún bloqueado',
  'slot.titel': 'Este capítulo aún está bloqueado',
  'slot.uitleg': 'Tu profesor lo abrirá cuando empiece la clase.',
  'slot.komtEraan': 'Las lecciones de este capítulo llegan pronto.',
  'tijd.minuten': '{aantal} min',
  'tijd.uren': '{uren} h',
  'tijd.urenMinuten': '{uren} h {minuten} min',
  'profiel.taal.kop': 'El idioma de tus lecciones',
  'profiel.taal.uitleg': 'Elige el idioma en el que quieres leer las explicaciones. Tus respuestas las escribes en neerlandés.',
  'profiel.taal.nederlands': 'Solo neerlandés',
  'profiel.taal.opgeslagen': 'Guardado.',
  'profiel.taal.mislukt': 'No se pudo guardar. Inténtalo otra vez dentro de un momento.'
};

// Arabisch staat op verzoek van Kevin in dezelfde leesrichting als de rest van
// het scherm (links naar rechts). De Arabische woorden zelf zet de browser
// vanzelf goed om; alleen de opmaak van de pagina draait niet mee.
const AR = {
  'lesstof.kop': 'الدروس',
  'lesstof.titel': 'دروسك',
  'lesstof.laden': 'جارٍ تحميل الدروس',
  'lesstof.leeg.titel': 'لا توجد دروس جاهزة لصفك بعد',
  'lesstof.leeg.tekst': 'سيضع معلمك دروسًا هنا قريبًا.',
  'verder.kop': 'أكمل من حيث توقفت',
  'verder.klaar.titel': 'أنت على اطلاع',
  'verder.klaar.tekst': 'أنهيت كل ما كان جاهزًا. اختر فصلًا في الأسفل لتقرأه من جديد.',
  'status.nietBegonnen': 'لم يبدأ بعد',
  'knop.beginnen': 'ابدأ',
  'knop.gaVerder': 'تابع',
  'knop.openen': 'افتح',
  'knop.bekijkTerug': 'انظر مرة أخرى',
  'knop.verder': 'التالي',
  'knop.start': 'ابدأ',
  'knop.opnieuw': 'مرة أخرى',
  'hoofdstuk.kop': 'الفصل',
  'hoofdstuk.kopMetNummer': 'الفصل {nummer}',
  'hoofdstuk.af': 'هذا الفصل مكتمل',
  'hoofdstuk.aantal.een': 'فصل واحد',
  'hoofdstuk.aantal.meer': '{aantal} فصول',
  'paragraaf.aantal.een': 'فقرة واحدة',
  'paragraaf.aantal.meer': '{aantal} فقرات',
  'onderdeel.aantal.een': 'جزء واحد',
  'onderdeel.aantal.meer': '{aantal} أجزاء',
  'onderdeel.geen': 'لا توجد أجزاء منشورة بعد',
  'onderdeel.af': 'أنجزت {done} من {total} أجزاء',
  'leerdoel.aantal.een': 'هدف واحد',
  'leerdoel.aantal.meer': '{aantal} أهداف',
  'rubriek.onderdelen': 'الأجزاء',
  'rubriek.voortgang': 'التقدم',
  'rubriek.introductie': 'مقدمة',
  'rubriek.voorkennis': 'معرفة سابقة',
  'rubriek.paragrafen': 'الفقرات',
  'rubriek.oefentoetsen': 'اختبارات تدريبية',
  'rubriek.toetsen': 'الاختبارات',
  'hoofdstuk.waarover': 'عن ماذا يتحدث هذا الفصل',
  'knop.opnieuwBekijken': 'انظر مرة أخرى',
  'knop.toonMinder': 'أظهر أقل',
  'knop.toonAlles': 'أظهر الكل ({aantal})',
  'knop.toonAllesPlus': 'أظهر الكل ({aantal}) - وأيضًا الفقرات الإضافية',
  'knop.startOnderdeel': 'ابدأ هذا الجزء',
  'knop.beginBijStap1': 'ابدأ من الخطوة 1',
  'knop.kopieerLink': 'انسخ الرابط',
  'knop.meerOpties': 'خيارات أخرى',
  'knop.terugNaarOverzicht': 'العودة إلى النظرة العامة',
  'status.af': 'مكتمل',
  'paragraaf.geenOnderdelen': 'لم يجهز معلمك أجزاءً لهذه الفقرة بعد.',
  'hoofdstuk.laden': 'جارٍ تحميل الفصل',
  'hoofdstuk.nietVoorJou.titel': 'هذا الفصل ليس جاهزًا لك',
  'hoofdstuk.nietVoorJou.tekst': 'ربما الرابط قديم، أو لم يشارك معلمك الفصل بعد.',
  'nogTeDoen.kop': 'ما زال عليك',
  'nogTeDoen.klaar': 'هذا الفصل مكتمل.',
  'nogTeDoen.rest': 'و{aantal} أخرى',
  'melding.linkGekopieerd': 'تم نسخ الرابط.',
  'melding.kopierenMislukt': 'لم ينجح النسخ.',
  'melding.kopierenKanNiet': 'النسخ لا يعمل في هذا المتصفح.',
  'rubriek.paragraaf': 'فقرة',
  'les.kop': 'درس',
  'les.leerdoelen': 'الأهداف',
  'les.inDitHoofdstuk': 'في هذا الفصل',
  'les.onderdeelVan': 'الجزء {nummer} من {totaal}',
  'les.terugNaarHoofdstuk': 'العودة إلى الفصل',
  'les.paragraafAfronden': 'أنهِ الفقرة',
  'les.volledigScherm': 'ملء الشاشة',
  'status.afgerond': 'مكتمل',
  'status.nogNietAf': 'غير مكتمل بعد',
  'knop.vorige': 'السابق',
  'knop.volgendeStap': 'الخطوة التالية',
  'les.afronden': 'أنهِ الدرس',
  'intro.watJeGaatLeren': 'ما الذي ستتعلمه:',
  'intro.stappen.een': 'خطوة واحدة',
  'intro.stappen.meer': '{aantal} خطوات',
  'plus.label': 'إضافي - اختياري',
  'plus.kort': 'إضافي',
  'plus.hoeftNiet': 'ليس إلزاميًا - لكن يمكنك',
  'plus.extraAf': 'إضافي: أنجزت {done} من {total}',
  'plus.staatKlaar': 'المواد الإضافية جاهزة إن أردت المزيد',
  'plus.uitleg': 'هذه الفقرة اختيارية. لا تُحسب ضمن فصلك ولا يلزم أن تنهيها لتتابع. '
    + 'ينصح بها إن أردت لاحقًا الانتقال إلى havo - وتكسب بها رموزًا أيضًا.',
  'slot.label': 'ما زال مقفلًا',
  'slot.titel': 'هذا الفصل ما زال مقفلًا',
  'slot.uitleg': 'سيفتحه معلمك عندما يبدأ الدرس.',
  'slot.komtEraan': 'دروس هذا الفصل قادمة قريبًا.',
  'tijd.minuten': '{aantal} دقيقة',
  'tijd.uren': '{uren} ساعة',
  'tijd.urenMinuten': '{uren} ساعة و{minuten} دقيقة',
  'profiel.taal.kop': 'لغة دروسك',
  'profiel.taal.uitleg': 'اختر اللغة التي تريد أن تقرأ بها الشرح. أما إجاباتك فتكتبها بالهولندية.',
  'profiel.taal.nederlands': 'الهولندية فقط',
  'profiel.taal.opgeslagen': 'تم الحفظ.',
  'profiel.taal.mislukt': 'لم يتم الحفظ. حاول مرة أخرى بعد قليل.'
};

const WOORDENBOEK = { nl: NL, el: EL, it: IT, uk: UK, en: EN, tr: TR, pl: PL, ro: RO, es: ES, ar: AR };

const vulIn = (tekst, waarden = {}) =>
  String(tekst).replace(/\{(\w+)\}/g, (heel, naam) => (
    Object.prototype.hasOwnProperty.call(waarden, naam) ? String(waarden[naam]) : heel
  ));

/**
 * De schermtekst bij een sleutel. Een lege taal, een onbekende taal of een
 * ontbrekende vertaling geeft het Nederlands terug.
 */
export const uiTekst = (sleutel, taal = '', waarden = {}) => {
  const code = String(taal || '').trim().toLowerCase();
  const tekst = WOORDENBOEK[code]?.[sleutel] ?? NL[sleutel];
  return tekst === undefined ? sleutel : vulIn(tekst, waarden);
};

/** Enkelvoud of meervoud, met het aantal erin. */
export const uiAantal = (basis, aantal = 0, taal = '', extra = {}) =>
  uiTekst(Number(aantal) === 1 ? `${basis}.een` : `${basis}.meer`, taal, { aantal, ...extra });

/**
 * Een studieduur in de taal van de leerling. Dezelfde vorm als
 * formatStudyDuration in studyRouteState.js, maar met vertaalde eenheden.
 */
export const uiStudieduur = (minuten = 0, taal = '') => {
  const totaal = Number(minuten) || 0;
  if (totaal <= 0) return '';
  if (totaal < 60) return uiTekst('tijd.minuten', taal, { aantal: totaal });
  const uren = Math.floor(totaal / 60);
  const rest = totaal % 60;
  return rest === 0
    ? uiTekst('tijd.uren', taal, { uren })
    : uiTekst('tijd.urenMinuten', taal, { uren, minuten: rest });
};

/**
 * Bewaakt dat elke taal uit LES_TALEN elke sleutel heeft en dat de
 * plaatshouders in een vertaling dezelfde zijn als in het Nederlands. Een
 * vergeten `{done}` valt anders pas op als een leerling naar een halve zin
 * kijkt, en een vergeten sleutel pas als er ineens Nederlands tussen staat.
 */
export const controleerWoordenboekCompleet = (talen = LES_TALEN) => {
  const problemen = [];
  const plaatshouders = (tekst) => (String(tekst || '').match(/\{\w+\}/g) || []).sort().join(',');

  talen.forEach(({ code }) => {
    const woorden = WOORDENBOEK[code];
    if (!woorden) {
      problemen.push(`${code}: geen woordenboek`);
      return;
    }

    Object.entries(NL).forEach(([sleutel, nederlands]) => {
      if (!woorden[sleutel]) {
        problemen.push(`${code}: sleutel ${sleutel} ontbreekt`);
        return;
      }
      if (plaatshouders(woorden[sleutel]) !== plaatshouders(nederlands)) {
        problemen.push(`${code}: andere plaatshouders bij ${sleutel}`);
      }
    });

    Object.keys(woorden).forEach((sleutel) => {
      if (!(sleutel in NL)) problemen.push(`${code}: sleutel ${sleutel} bestaat niet in het Nederlands`);
    });
  });

  return problemen;
};

export const UI_SLEUTELS = Object.keys(NL);
